configuration:
    db:
        connections:
            oracle: DSN=STUDENTSUCCESS;PWD=student_success
            mssql: DRIVER={SQL Server Native Client 11.0};SERVER=.\MASTER;DATABASE=RADAR_DW;UID=python;PWD=python

        queries:
            complete: select * from student_success.complete_vw@SM_SMDW_LINK where APROG_PROG_STATUS IN ('DC','CM') AND ACAD_PROG='UBACH' and basis_admit_code = 'N'

        cache: data_cache.pkl

        results: results.pkl

    logging:
        output_log: output.log


    genetic:
        mutation_rate: 0.02

    col_lists:
        one_hot_list:
            - GE_CRITICAL_THINKING_STATUS
            - GE_ENGLISH_COMPOSITION_STATUS
            - GE_ORAL_COMMUNICATIONS_STATUS
            - GE_MATH_STATUS
            - COLLEGE
            - DEPARTMENT
            - GENDER_DESC
            - ETHNICITY_GRP_IPA
            - MARITAL_STATUS
            - ELM_STATUS
            - EPT_STATUS
            - ADMIT_ACAD_LOAD
 #           - EARLY_START_DEST_STDNT
            - FIRST_COLLEGE
            - FIRST_DEPT
            - LAST_COLLEGE
            - LAST_DEPT
  #          - TOT_24_DEGR_UNITS_YEAR1
            - TOT_24_UNITS_YEAR1
            - MILITARY_STATUS
 #           - CSU_APP_ED_MOTHER
 #           - CSU_APP_ED_FATHER
#            - BASIS_ADMIT_CODE_SDESC
            - CSU_APP_ED_FATHER_LDESC
            - CSU_APP_ED_MOTHER_LDESC



        drop_col_list:
            - LAST_PLAN
            - FIRST_PLAN
            - DW_ROWRANK
            - HOME_COUNTRY
            - DISABLED
            - HOUSING_INTEREST
            - PROG_ADMIT_TERM
            - APLAN_ACAD_PLAN
            - EMPLID
            - ACAD_CAREER
            - ACAD_PROG
            - BASIS_ADMIT_CODE_SDESC
            - DW_CURRENTROW
            - BASIS_ADMIT_CODE
            - ADMIT_ACAD_LOAD_LDESC
            - AVG_TERM_UNITS_PASSED_GPA
  #          - TOT_DEGR_UNITS_YEAR1
            - AVG_TERM_UNITS_TOTAL
            - AVG_TERM_GPA
            - AVG_TERM_UNITS_TAKEN_GPA
            - AVG_TERM_GRADE_POINTS
            - TOT_UNITS_YEAR1
            - CSU_APP_ED_MOTHER
            - CSU_APP_ED_FATHER
            - ACTIVE_TERMS
            - ENROLLED_TERMS
 #           - TOT_24_DEGR_UNITS_YEAR1__Yes
 #           - TOT_24_DEGR_UNITS_YEAR1__No
 #           - TOT_24_UNITS_YEAR1__Yes
 #          - TOT_24_UNITS_YEAR1__No



        outcome_list:
            - APROG_PROG_STATUS
            - RETAIN_1_YEAR
            - RETAIN_2_YEAR
            - RETAIN_3_YEAR
            - GRADUATE_4_YEARS
            - GRADUATE_5_YEARS
            - GRADUATE_6_YEARS
            - EXACT_2_YEARS
            - EXACT_3_YEARS
            - EXACT_4_YEARS
            - EXACT_5_YEARS
            - EXACT_6_YEARS
            - EXACT_7_YEARS
            - EXACT_8_YEARS
            - WITHIN_2_YEARS
            - WITHIN_3_YEARS
            - WITHIN_4_YEARS
            - WITHIN_5_YEARS
            - WITHIN_6_YEARS
            - WITHIN_7_YEARS
            - WITHIN_8_YEARS

