configuration:
    db:
        connections:
            oracle: DSN=STUDENTSUCCESS;PWD=student_success
            mssql: DRIVER={SQL Server Native Client 11.0};SERVER=.\MASTER;DATABASE=RADAR_DW;UID=python;PWD=python

        queries:
            complete: select DECODE(APROG_PROG_STATUS, 'DC', 0, 1) AS GRADUATED, a.* from student_success.complete_vw@SM_SMDW_LINK a where APROG_PROG_STATUS IN ('DC','CM') AND PROG_ADMIT_TERM BETWEEN '0984' AND '2104' AND ACAD_PROG='UBACH' and ADMIT_TYPE IN ('5')
        cache: data_cache.pkl

        results: results.pkl

    logging:
        output_log: output.log


    genetic:
        mutation_rate: 0.02

    col_lists:
        one_hot_list:
            - GE_CRITICAL_THINKING_STATUS
            - GE_ENGLISH_COMPOSITION_STATUS
            - GE_ORAL_COMMUNICATIONS_STATUS
            - GE_MATH_STATUS
#            - COLLEGE
#            - DEPARTMENT
            - GENDER_DESC
            - ETHNICITY_GRP_IPA
            - MARITAL_STATUS
            - ELM_STATUS
            - EPT_STATUS
            - ADMIT_ACAD_LOAD
 #           - EARLY_START_DEST_STDNT
            - FIRST_COLLEGE
            - FIRST_DEPT
            - LAST_COLLEGE
            - LAST_DEPT
            - FIRST_PLAN
            - LAST_PLAN
  #          - TOT_24_DEGR_UNITS_YEAR1
#            - TOT_24_UNITS_YEAR1
            - MILITARY_STATUS
 #           - CSU_APP_ED_MOTHER
 #           - CSU_APP_ED_FATHER
#            - BASIS_ADMIT_CODE_SDESC
            - CSU_APP_ED_FATHER_LDESC
            - CSU_APP_ED_MOTHER_LDESC
            - SUPPORT_STATUS_FIRST
            - SUPPORT_STATUS_LAST
            - ADMIT_TYPE_LDESC

            - ELM_STATUS_LDESC
            - EPT_STATUS_LDESC
            - DEGREE_OBJECTIVE_SDESC
            - BASIS_ADMIT_CODE_SDESC
            - ADMIT_ACAD_LOAD_LDESC

        label_encode_list:
            - APROG_PROG_STATUS

        drop_col_list:
        # GPA
            - PREV_TERM_GPA
            - LAST_TERM_GPA
            - MAX_TERM_GPA
            - AVG_CSUSM_GPA
            - MIN_TERM_GPA
            - MAX_CSUSM_GPA
            - AVG_TERM_GPA
            - MIN_CSUSM_GPA
            - CSUSM_GPA_FINAL
            - CSUSM_GPA_FIRST_TERM
            - MAX_CUM_GPA
            - AVG_CUM_GPA
            - MIN_CUM_GPA
            - CSUSM_GPA_FIRST_YEAR
            - LAST_DEPT__Undeclared
            - LAST_PLAN__UNDL
        # UNITS
            - AVG_TERM_UNITS_TOTAL
            - AVG_TERM_UNITS_PASSED_GPA
            - AVG_TERM_UNITS_TAKEN_GPA
            - TOT_24_DEGR_UNITS_YEAR1
            - TOT_24_UNITS_YEAR1
            - TOT_DEGR_UNITS_YEAR1
            - TOT_UNITS_YEAR1
            - AVG_TERM_GRADE_POINTS
        # TERMS
            - ACTIVE_TERMS
            - ENROLLED_TERMS

            - DW_ROWRANK
            - HOME_COUNTRY
            - DISABLED
            - HOUSING_INTEREST
            - PROG_ADMIT_TERM
            - APLAN_ACAD_PLAN
            - EMPLID
            - ACAD_CAREER
            - ACAD_PROG
            - DW_CURRENTROW
            - BASIS_ADMIT_CODE
            - CSU_APP_ED_MOTHER
            - CSU_APP_ED_FATHER
            - RESIDENCY_CODE_LDESC




        impute_columns:
            - HS_GPA
            - SAT_VERBAL
            - SAT_MATH


        outcome_list:
            - APROG_PROG_STATUS
            - RETAIN_1_YEAR
            - RETAIN_2_YEAR
            - RETAIN_3_YEAR
            - EXACT_2_YEARS
            - EXACT_3_YEARS
            - EXACT_4_YEARS
            - EXACT_5_YEARS
            - EXACT_6_YEARS
            - EXACT_7_YEARS
            - EXACT_8_YEARS
            - WITHIN_2_YEARS
            - WITHIN_3_YEARS
            - WITHIN_4_YEARS
            - WITHIN_5_YEARS
            - WITHIN_6_YEARS
            - WITHIN_7_YEARS
            - WITHIN_8_YEARS
            - GRADUATED

