configuration:
    db:
        connections:
            oracle: DSN=STUDENTSUCCESS;PWD=student_success
            mssql: DRIVER={SQL Server Native Client 11.0};SERVER=.\MASTER;DATABASE=RADAR_DW;UID=python;PWD=python

        queries:
            complete: select * from student_success.complete_vw@SM_SMDW_LINK where APROG_PROG_STATUS IN ('DC','CM') AND ACAD_PROG='UBACH' and basis_admit_code = 'N'

        cache: data_cache.pkl

        results: results.pkl

    logging:
        output_log: output.log


    genetic:
        mutation_rate: 0.02

    col_lists:
        one_hot_list:
            - GE_CRITICAL_THINKING_STATUS
            - GE_ENGLISH_COMPOSITION_STATUS
            - GE_ORAL_COMMUNICATIONS_STATUS
            - GE_MATH_STATUS
            - COLLEGE
            - DEPARTMENT
            - GENDER_DESC
            - ETHNICITY_GRP_IPA
            - MARITAL_STATUS
            - ELM_STATUS
            - EPT_STATUS
            - ADMIT_ACAD_LOAD
            - ATHL
            - CAMP
            - EARLY_START_DEST_STDNT
            - EOP
            - FIRST_COLLEGE
            - FIRST_DEPT
            - LAST_COLLEGE
            - LAST_DEPT
            - FYP_COURSE_COMPLETED
            - GEL101_COURSE_COMPLETED
            - GEL_COURSE_COMPLETED
            - ON_CAMPUS_JOB_EVER
            - RECEIVED_ADVISING
            - TOT_24_DEGR_UNITS_YEAR1
            - TOT_24_UNITS_YEAR1
            - MILITARY_STATUS
            - CSU_APP_ED_MOTHER
            - CSU_APP_ED_FATHER



        drop_col_list:
            - LAST_PLAN
            - FIRST_PLAN
            - DW_ROWRANK
            - HOME_COUNTRY
            - DISABLED
            - HOUSING_INTEREST
            - PROG_ADMIT_TERM
            - APLAN_ACAD_PLAN
            - EMPLID
            - ACAD_CAREER
            - ACAD_PROG
            - BASIS_ADMIT_CODE_SDESC
            - DW_CURRENTROW
            - BASIS_ADMIT_CODE
            - ADMIT_ACAD_LOAD_LDESC
            - CSU_APP_ED_FATHER_LDESC
            - CSU_APP_ED_MOTHER_LDESC
            - AVG_TERM_UNITS_PASSED_GPA
            - TOT_DEGR_UNITS_YEAR1
            - AVG_TERM_UNITS_TOTAL
            - AVG_TERM_GPA
            - TOT_24_UNITS_YEAR1__Yes


        outcome_list:
            - APROG_PROG_STATUS
            - RETAIN_1_YEAR
            - RETAIN_2_YEAR
            - RETAIN_3_YEAR
            - GRADUATE_4_YEARS
            - GRADUATE_5_YEARS
            - GRADUATE_6_YEARS

