configuration:
    db:
        connections:
            oracle: DSN=STUDENTSUCCESS;PWD=student_success
            mssql: DRIVER={SQL Server Native Client 11.0};SERVER=.\MASTER;DATABASE=RADAR_DW;UID=python;PWD=python

        queries:
            complete: select * from student_success.complete_vw@SM_SMDW_LINK where APROG_PROG_STATUS IN ('DC','CM') AND ACAD_PROG='UBACH'

    col_lists:
        one_hot_list:
            - GE_CRITICAL_THINKING_STATUS
            - GE_ENGLISH_COMPOSITION_STATUS
            - GE_ORAL_COMMUNICATIONS_STATUS
            - GE_MATH_STATUS
            - COLLEGE
            - DEPARTMENT
            - GENDER_DESC
            - ETHNICITY_GRP_IPA
            - MARITAL_STATUS
            - HOME_COUNTRY

        drop_col_list:
            - DISABLED
            - HOUSING_INTEREST
            - PROG_ADMIT_TERM
            - ELM_STATUS
            - EPT_STATUS
            - APLAN_ACAD_PLAN
            - EMPLID
            - ACAD_CAREER
            - ACAD_PROG
            - BASIS_ADMIT_CODE_SDESC
            - DW_CURRENTROW

        outcome_list:
            - APROG_PROG_STATUS
            - RETAIN_1_YEAR
            - RETAIN_2_YEAR
            - RETAIN_3_YEAR
            - GRADUATE_4_YEARS
            - GRADUATE_5_YEARS
            - GRADUATE_6_YEARS