--------------------------------------------------------
--  File created - Friday-October-14-2016
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View COMPLETE_VW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "STUDENT_SUCCESS"."COMPLETE_VW" ("DW_CURRENTROW", "EMPLID", "MARITAL_STATUS", "DISABLED", "HOME_COUNTRY", "GENDER_DESC", "ETHNICITY_GRP_IPA", "GRADUATE_6_YEARS", "GRADUATE_5_YEARS", "GRADUATE_4_YEARS", "RETAIN_2_YEAR", "RETAIN_1_YEAR", "RETAIN_3_YEAR", "PROG_ADMIT_TERM", "ACAD_PROG", "ACAD_CAREER", "APROG_PROG_STATUS", "APLAN_ACAD_PLAN", "BASIS_ADMIT_CODE_SDESC", "BASIS_ADMIT_CODE", "ADMIT_TYPE", "ACADEMIC_LEVEL", "HOUSING_INTEREST", "HS_PREP_UNITS_ENGL", "HS_PREP_UNITS_MATH", "HS_PREP_UNITS_LAB_SCIENCE", "HS_PREP_UNITS_FOREIGN_LANGUAGE", "HS_PREP_UNITS_VISUAL_PERF_ARTS", "HS_PREP_UNITS_SOCSCI_HST_GOVT", "HS_PREP_UNITS_ELECTIVE", "GE_ENGLISH_COMPOSITION_STATUS", "GE_CRITICAL_THINKING_STATUS", "GE_MATH_STATUS", "GE_ORAL_COMMUNICATIONS_STATUS", "ELM_STATUS", "EPT_STATUS", "DEPARTMENT", "COLLEGE", "TOTAL_12UNITS_COMP_1YR", "TOTAL_24UNITS_COMP_1YR", "TOTAL_UNITS_COMP_1YR", "DEGREE_12UNITS_COMP_1YR", "DEGREE_24UNITS_COMP_1YR", "DEGREE_UNITS_COMP_1YR", "F_COUNT_FIRST_TERM", "COMPLETED_GEL101", "SAT_MATH", "SAT_VERBAL", "HIP_CAMP", "HIP_EARLYSTART", "HIP_EMPLOYMENT", "HIP_EOP", "HIP_GEL", "AGE_AT_ENTRY") AS
  SELECT a.DW_CURRENTROW,
  b.EMPLID,
  b.MARITAL_STATUS,
  --b.BIRTHDATE,

 -- b.MILITARY_STATUS,
  b.DISABLED,
  b.HOME_COUNTRY,
 -- b.HOME_CITY,
 -- b.HOME_STATE,
  b.GENDER_DESC,
  b.ETHNICITY_GRP_IPA,
  DECODE(a.APROG_PROG_STATUS,'DC', 0, c.GRADUATE_6_YEARS) GRADUATE_6_YEARS,
DECODE(a.APROG_PROG_STATUS,'DC', 0, c.GRADUATE_5_YEARS) GRADUATE_5_YEARS,
DECODE(a.APROG_PROG_STATUS,'DC', 0, c.GRADUATE_4_YEARS) GRADUATE_4_YEARS,
 -- c.COMPLETION_TERM,
  c.RETAIN_2_YEAR,
  c.RETAIN_1_YEAR,
  c.RETAIN_3_YEAR,
  c.PROG_ADMIT_TERM,
  c.ACAD_PROG,
  c.ACAD_CAREER,
  a.APROG_PROG_STATUS,
 -- a.APROG_PROG_REASON,
  a.APLAN_ACAD_PLAN,
 -- a.DW_FIRSTROW,
 -- a.DW_ROWRANK,
 -- a.DW_STARTDATE,
 -- a.DW_ENDDATE,
  admit_dtl.BASIS_ADMIT_CODE_SDESC,
  admit_dtl.BASIS_ADMIT_CODE,
  application.ADMIT_TYPE,
  application.ACADEMIC_LEVEL,
  application.HOUSING_INTEREST,
  application.HS_PREP_UNITS_ENGL,
  application.HS_PREP_UNITS_MATH,
  application.HS_PREP_UNITS_LAB_SCIENCE,
  application.HS_PREP_UNITS_FOREIGN_LANGUAGE,
  application.HS_PREP_UNITS_VISUAL_PERF_ARTS,
  application.HS_PREP_UNITS_SOCSCI_HST_GOVT,
  application.HS_PREP_UNITS_ELECTIVE,
  application.GE_ENGLISH_COMPOSITION_STATUS,
  application.GE_CRITICAL_THINKING_STATUS,
  application.GE_MATH_STATUS,
  application.GE_ORAL_COMMUNICATIONS_STATUS,
  --application.INSTITUTION_OF_ORIGIN,
  --application.DEGREE_OBJECTIVE,
  --application.CREDENTIAL_STATUS,
  --application.RESIDENCY_STATUS,
  application.ELM_STATUS,
  application.EPT_STATUS,
  dept.department,
  dept.college,
  lead.TOTAL_12UNITS_COMP_1YR,
  lead.TOTAL_24UNITS_COMP_1YR,
  lead.TOTAL_UNITS_COMP_1YR,
  lead.DEGREE_12UNITS_COMP_1YR,
  lead.DEGREE_24UNITS_COMP_1YR,
  lead.DEGREE_UNITS_COMP_1YR,
  lead.F_COUNT_FIRST_TERM,
  lead.COMPLETED_GEL101,
  scores.MATH_TEST_SCORE AS SAT_MATH,
  scores.VERBAL_TEST_SCORE as SAT_VERBAL,
  hips.HIP_CAMP,
  hips.HIP_EARLYSTART,
  hips.HIP_EMPLOYMENT,
  hips.HIP_EOP,
  hips.HIP_GEL,
   ROUND((term.term_begin_date - b.BIRTHDATE)/365) AS AGE_AT_ENTRY
FROM STUDENT_SUCCESS.STG_ACADEMICPROGRAMPLAN a
INNER JOIN sa.cc_personal_data_dtl b
ON a.APROG_EMPLID = b.EMPLID
INNER JOIN SA.REC_STUDENT_OUTCOMES c
ON a.APROG_EMPLID           = c.EMPLID
AND a.APROG_ACAD_CAREER     = c.ACAD_CAREER
AND a.APROG_ACAD_PROG       = c.ACAD_PROG
AND a.APROG_PROG_ADMIT_TERM = c.PROG_ADMIT_TERM
INNER JOIN SA.ADM_BASIS_ADMIT_DTL admit_dtl
ON a.APROG_EMPLID           = admit_dtl.EMPLID
AND a.APROG_ACAD_CAREER     = admit_dtl.ACAD_CAREER
AND a.APROG_ACAD_PROG       = admit_dtl.ACAD_PROGRAM
AND a.APROG_PROG_ADMIT_TERM = admit_dtl.ADMIT_TERM
INNER JOIN SA.ADM_APP_DATA_DTL application
ON a.APROG_EMPLID           = application.EMPLID
AND a.APROG_ACAD_CAREER     = application.ACAD_CAREER
AND a.APROG_PROG_ADMIT_TERM = application.ADMIT_TERM
INNER JOIN SA.AS_TERM_TBL term
ON a.APROG_PROG_ADMIT_TERM = term.term
INNER JOIN SA.AS_ACAD_PLAN_TBL dept
ON a.APLAN_ACAD_PLAN = dept.acad_plan
INNER JOIN SA.REC_STUDENT_LEADING_INDICATORS lead
ON a.APROG_EMPLID           = lead.EMPLID
AND a.APROG_ACAD_CAREER     = lead.ACAD_CAREER
AND a.APROG_ACAD_PROG       = lead.ACAD_PROG
AND a.APROG_PROG_ADMIT_TERM = lead.PROG_ADMIT_TERM
LEFT JOIN STUDENT_SUCCESS.TEST_SCORES_VW scores
ON a.aprog_emplid = scores.emplid
LEFT JOIN STUDENT_SUCCESS.HIPS_VW hips
ON a.aprog_emplid = hips.emplid
and scores.TEST_ID='SAT'
WHERE a.DW_CURRENTROW       = 1
--AND b.EMPLID                = '000017781';
--------------------------------------------------------
--  DDL for View COMPLET_VW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "STUDENT_SUCCESS"."COMPLET_VW" ("APROG_EMPLID", "APROG_ACAD_CAREER", "APROG_ACAD_CAREER_SDESC", "APROG_ACAD_CAREER_LDESC", "APROG_STDNT_CAR_NBR", "APROG_EFFDT", "APROG_EFFSEQ", "APROG_INSTITUTION", "APROG_INSTITUTION_SDESC", "APROG_INSTITUTION_LDESC", "APROG_ACAD_GROUP", "APROG_ACAD_GROUP_SDESC", "APROG_ACAD_GROUP_LDESC", "APROG_ACAD_PROG", "APROG_ACAD_PROG_SDESC", "APROG_ACAD_PROG_LDESC", "APROG_PROG_STATUS", "APROG_PROG_STATUS_SDESC", "APROG_PROG_STATUS_LDESC", "APROG_PROG_ACTION", "APROG_PROG_ACTION_SDESC", "APROG_PROG_ACTION_LDESC", "APROG_ACTION_DT", "APROG_PROG_REASON", "APROG_PROG_REASON_SDESC", "APROG_PROG_REASON_LDESC", "APROG_PROG_ADMIT_TERM", "APROG_PROG_ADMIT_TERM_SDESC", "APROG_PROG_ADMIT_TERM_LDESC", "APROG_EXP_GRAD_TERM", "APROG_EXP_GRAD_TERM_SDESC", "APROG_EXP_GRAD_TERM_LDESC", "APROG_REQ_TERM", "APROG_REQ_TERM_SDESC", "APROG_REQ_TERM_LDESC", "APROG_CAMPUS", "APROG_CAMPUS_SDESC", "APROG_CAMPUS_LDESC", "APROG_DEGR_CHECKOUT_STAT", "APROG_DEGR_CHECKOUT_SDESC", "APROG_DEGR_CHECKOUT_LDESC", "APROG_ADM_APPL_NBR", "APROG_APPL_PROG_NBR", "APROG_CIP_CODE", "APROG_HEGIS_CODE", "APLAN_ACAD_PLAN", "APLAN_ACAD_PLAN_SDESC", "APLAN_ACAD_PLAN_LDESC", "APLAN_ACAD_PLAN_TYPE", "APLAN_PLAN_TYPE_SDESC", "APLAN_PLAN_TYPE_LDESC", "APLAN_DECLARE_DT", "APLAN_CIP_CODE", "APLAN_HEGIS_CODE", "APLAN_SEQUENCE", "APLAN_REQ_TERM", "APLAN_REQ_TERM_SDESC", "APLAN_REQ_TERM_LDESC", "DW_STARTDATE", "DW_ENDDATE", "DW_ROWRANK", "DW_FIRSTROW", "DW_CURRENTROW", "EMPLID", "CAMPUS_ID", "GENDER", "MARITAL_STATUS", "BIRTHDATE", "BIRTHPLACE", "BIRTHSTATE", "BIRTHCOUNTRY", "DATE_OF_DEATH", "FERPA_STDNT_PRIVACY", "CSU_ERS_ASSIGNED_ID", "MILITARY_STATUS", "VA_BENEFIT", "DISABLED", "NATIONAL_ID", "NAME_PRIMARY", "NAME_PRIMARY_PREFIX", "NAME_PRIMARY_SUFFIX", "LAST_NAME_PRIMARY", "FIRST_NAME_PRIMARY", "MIDDLE_NAME_PRIMARY", "NAME_PREFERRED", "NAME_PREFERRED_PREFIX", "NAME_PREFERRED_SUFFIX", "PREF_LAST_NAME", "PREF_FIRST_NAME", "PREF_MIDDLE_NAME", "HOME_COUNTRY", "HOME_COUNTRY_LDESC", "HOME_COUNTRY_SDESC", "HOME_ADDRESS1", "HOME_ADDRESS2", "HOME_CITY", "HOME_STATE", "HOME_STATE_DESC", "HOME_POSTAL_ZIP", "HOME_PHONE_CNTRY_CODE", "HOME_PHONE_NBR", "GENDER_DESC", "MARITAL_STATUS_SDESC", "MARITAL_STATUS_LDESC", "BIRTHCOUNTRY_SDESC", "BIRTHCOUNTRY_LDESC", "ETHNIC_GRP_PRIMARY", "ETHNIC_GRP_PRIMARY_SDESC", "ETHNIC_GRP_PRIMARY_LDESC", "EMAIL_PREFERRED", "ETHNICITY_PRIMARY", "ETHNICITY_PRIMARY_SDESC", "ETHNICITY_PRIMARY_LDESC", "SEVIS_ID", "EMPL_WAIVE_DATA_PROTECTION", "MILITARY_STATUS_SDESC", "MILITARY_STATUS_LDESC", "MILITARY_DISCHAGE_DATE", "EMERGENCY_CONTACT_NAME", "EMERGENCY_RELATIONSHIP", "EMERGENCY_COUNTRY", "EMERGENCY_ADDRESS1", "EMERGENCY_ADDRESS2", "EMERGENCY_CITY", "EMERGENCY_STATE", "EMERGENCY_POSTAL_ZIP", "EMERGENCY_PHONE_PRIMARY", "PERM_RECORD_NBR", "NAME_PREVIOUS", "NAME_PREVIOUS_SUFFIX", "VA_DISABLED_VET", "MAIL_COUNTRY_SDESC", "MAIL_COUNTRY", "MIDDLE_NAME_PREFERRED", "FIRST_NAME_PREFERRED", "LAST_NAME_PREFERRED", "MAIL_STATE_DESC", "MAIL_STATE", "MAIL_COUNTY", "MAIL_CITY", "MAIL_ADDRESS4", "MAIL_ADDRESS3", "MAIL_ADDRESS2", "MAIL_ADDRESS1", "MAIL_COUNTRY_LDESC", "MAIL_POSTAL_ZIP", "PERM_PHONE_EXTENSION", "PERM_PHONE_NBR", "PERM_PHONE_CNTRY_CODE", "PERM_GEO_CODE", "PERM_POSTAL_ZIP", "PERM_STATE_DESC", "PERM_STATE", "PERM_COUNTY", "PERM_CITY", "PERM_ADDRESS4", "PERM_ADDRESS3", "PERM_ADDRESS2", "PERM_ADDRESS1", "PERM_COUNTRY_LDESC", "PERM_COUNTRY_SDESC", "PERM_COUNTRY", "MAIL_PHONE_EXTENSION", "MAIL_PHONE_NBR", "MAIL_PHONE_CNTRY_CODE", "MAIL_GEO_CODE", "ETHNICITY_GRP", "ETHNICITY_GRP_IPA", "ETHNICITY_GRP_URM_IPA", "CITIZENSHIP_CNTRY", "NONRESIDENT_ALIEN") AS
  select "APROG_EMPLID","APROG_ACAD_CAREER","APROG_ACAD_CAREER_SDESC","APROG_ACAD_CAREER_LDESC","APROG_STDNT_CAR_NBR","APROG_EFFDT","APROG_EFFSEQ","APROG_INSTITUTION","APROG_INSTITUTION_SDESC","APROG_INSTITUTION_LDESC","APROG_ACAD_GROUP","APROG_ACAD_GROUP_SDESC","APROG_ACAD_GROUP_LDESC","APROG_ACAD_PROG","APROG_ACAD_PROG_SDESC","APROG_ACAD_PROG_LDESC","APROG_PROG_STATUS","APROG_PROG_STATUS_SDESC","APROG_PROG_STATUS_LDESC","APROG_PROG_ACTION","APROG_PROG_ACTION_SDESC","APROG_PROG_ACTION_LDESC","APROG_ACTION_DT","APROG_PROG_REASON","APROG_PROG_REASON_SDESC","APROG_PROG_REASON_LDESC","APROG_PROG_ADMIT_TERM","APROG_PROG_ADMIT_TERM_SDESC","APROG_PROG_ADMIT_TERM_LDESC","APROG_EXP_GRAD_TERM","APROG_EXP_GRAD_TERM_SDESC","APROG_EXP_GRAD_TERM_LDESC","APROG_REQ_TERM","APROG_REQ_TERM_SDESC","APROG_REQ_TERM_LDESC","APROG_CAMPUS","APROG_CAMPUS_SDESC","APROG_CAMPUS_LDESC","APROG_DEGR_CHECKOUT_STAT","APROG_DEGR_CHECKOUT_SDESC","APROG_DEGR_CHECKOUT_LDESC","APROG_ADM_APPL_NBR","APROG_APPL_PROG_NBR","APROG_CIP_CODE","APROG_HEGIS_CODE","APLAN_ACAD_PLAN","APLAN_ACAD_PLAN_SDESC","APLAN_ACAD_PLAN_LDESC","APLAN_ACAD_PLAN_TYPE","APLAN_PLAN_TYPE_SDESC","APLAN_PLAN_TYPE_LDESC","APLAN_DECLARE_DT","APLAN_CIP_CODE","APLAN_HEGIS_CODE","APLAN_SEQUENCE","APLAN_REQ_TERM","APLAN_REQ_TERM_SDESC","APLAN_REQ_TERM_LDESC","DW_STARTDATE","DW_ENDDATE","DW_ROWRANK","DW_FIRSTROW","DW_CURRENTROW","EMPLID","CAMPUS_ID","GENDER","MARITAL_STATUS","BIRTHDATE","BIRTHPLACE","BIRTHSTATE","BIRTHCOUNTRY","DATE_OF_DEATH","FERPA_STDNT_PRIVACY","CSU_ERS_ASSIGNED_ID","MILITARY_STATUS","VA_BENEFIT","DISABLED","NATIONAL_ID","NAME_PRIMARY","NAME_PRIMARY_PREFIX","NAME_PRIMARY_SUFFIX","LAST_NAME_PRIMARY","FIRST_NAME_PRIMARY","MIDDLE_NAME_PRIMARY","NAME_PREFERRED","NAME_PREFERRED_PREFIX","NAME_PREFERRED_SUFFIX","PREF_LAST_NAME","PREF_FIRST_NAME","PREF_MIDDLE_NAME","HOME_COUNTRY","HOME_COUNTRY_LDESC","HOME_COUNTRY_SDESC","HOME_ADDRESS1","HOME_ADDRESS2","HOME_CITY","HOME_STATE","HOME_STATE_DESC","HOME_POSTAL_ZIP","HOME_PHONE_CNTRY_CODE","HOME_PHONE_NBR","GENDER_DESC","MARITAL_STATUS_SDESC","MARITAL_STATUS_LDESC","BIRTHCOUNTRY_SDESC","BIRTHCOUNTRY_LDESC","ETHNIC_GRP_PRIMARY","ETHNIC_GRP_PRIMARY_SDESC","ETHNIC_GRP_PRIMARY_LDESC","EMAIL_PREFERRED","ETHNICITY_PRIMARY","ETHNICITY_PRIMARY_SDESC","ETHNICITY_PRIMARY_LDESC","SEVIS_ID","EMPL_WAIVE_DATA_PROTECTION","MILITARY_STATUS_SDESC","MILITARY_STATUS_LDESC","MILITARY_DISCHAGE_DATE","EMERGENCY_CONTACT_NAME","EMERGENCY_RELATIONSHIP","EMERGENCY_COUNTRY","EMERGENCY_ADDRESS1","EMERGENCY_ADDRESS2","EMERGENCY_CITY","EMERGENCY_STATE","EMERGENCY_POSTAL_ZIP","EMERGENCY_PHONE_PRIMARY","PERM_RECORD_NBR","NAME_PREVIOUS","NAME_PREVIOUS_SUFFIX","VA_DISABLED_VET","MAIL_COUNTRY_SDESC","MAIL_COUNTRY","MIDDLE_NAME_PREFERRED","FIRST_NAME_PREFERRED","LAST_NAME_PREFERRED","MAIL_STATE_DESC","MAIL_STATE","MAIL_COUNTY","MAIL_CITY","MAIL_ADDRESS4","MAIL_ADDRESS3","MAIL_ADDRESS2","MAIL_ADDRESS1","MAIL_COUNTRY_LDESC","MAIL_POSTAL_ZIP","PERM_PHONE_EXTENSION","PERM_PHONE_NBR","PERM_PHONE_CNTRY_CODE","PERM_GEO_CODE","PERM_POSTAL_ZIP","PERM_STATE_DESC","PERM_STATE","PERM_COUNTY","PERM_CITY","PERM_ADDRESS4","PERM_ADDRESS3","PERM_ADDRESS2","PERM_ADDRESS1","PERM_COUNTRY_LDESC","PERM_COUNTRY_SDESC","PERM_COUNTRY","MAIL_PHONE_EXTENSION","MAIL_PHONE_NBR","MAIL_PHONE_CNTRY_CODE","MAIL_GEO_CODE","ETHNICITY_GRP","ETHNICITY_GRP_IPA","ETHNICITY_GRP_URM_IPA","CITIZENSHIP_CNTRY","NONRESIDENT_ALIEN" from STUDENT_SUCCESS.STG_ACADEMICPROGRAMPLAN a join sa.cc_personal_data_dtl b on a.aprog_emplid = b.emplid where dw_currentrow=1;
--------------------------------------------------------
--  DDL for View HIPS_VW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "STUDENT_SUCCESS"."HIPS_VW" ("EMPLID", "HIP_EMPLOYMENT", "HIP_EOP", "HIP_GEL", "HIP_EARLYSTART", "HIP_CAMP") AS
  select "EMPLID","HIP_EMPLOYMENT","HIP_EOP","HIP_GEL","HIP_EARLYSTART","HIP_CAMP" from
(select emplid, hip from sa.rec_student_hips)
PIVOT
(MAX(1) for HIP IN ('EMP' as HIP_EMPLOYMENT,'EOP' as HIP_EOP,'GEL' as HIP_GEL,'ERLY' as HIP_EARLYSTART,'CAMP' as HIP_CAMP));
--------------------------------------------------------
--  DDL for View STG_ACADEMICPROGRAMPLAN
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "STUDENT_SUCCESS"."STG_ACADEMICPROGRAMPLAN" ("APROG_EMPLID", "APROG_ACAD_CAREER", "APROG_ACAD_CAREER_SDESC", "APROG_ACAD_CAREER_LDESC", "APROG_STDNT_CAR_NBR", "APROG_EFFDT", "APROG_EFFSEQ", "APROG_INSTITUTION", "APROG_INSTITUTION_SDESC", "APROG_INSTITUTION_LDESC", "APROG_ACAD_GROUP", "APROG_ACAD_GROUP_SDESC", "APROG_ACAD_GROUP_LDESC", "APROG_ACAD_PROG", "APROG_ACAD_PROG_SDESC", "APROG_ACAD_PROG_LDESC", "APROG_PROG_STATUS", "APROG_PROG_STATUS_SDESC", "APROG_PROG_STATUS_LDESC", "APROG_PROG_ACTION", "APROG_PROG_ACTION_SDESC", "APROG_PROG_ACTION_LDESC", "APROG_ACTION_DT", "APROG_PROG_REASON", "APROG_PROG_REASON_SDESC", "APROG_PROG_REASON_LDESC", "APROG_PROG_ADMIT_TERM", "APROG_PROG_ADMIT_TERM_SDESC", "APROG_PROG_ADMIT_TERM_LDESC", "APROG_EXP_GRAD_TERM", "APROG_EXP_GRAD_TERM_SDESC", "APROG_EXP_GRAD_TERM_LDESC", "APROG_REQ_TERM", "APROG_REQ_TERM_SDESC", "APROG_REQ_TERM_LDESC", "APROG_CAMPUS", "APROG_CAMPUS_SDESC", "APROG_CAMPUS_LDESC", "APROG_DEGR_CHECKOUT_STAT", "APROG_DEGR_CHECKOUT_SDESC", "APROG_DEGR_CHECKOUT_LDESC", "APROG_ADM_APPL_NBR", "APROG_APPL_PROG_NBR", "APROG_CIP_CODE", "APROG_HEGIS_CODE", "APLAN_ACAD_PLAN", "APLAN_ACAD_PLAN_SDESC", "APLAN_ACAD_PLAN_LDESC", "APLAN_ACAD_PLAN_TYPE", "APLAN_PLAN_TYPE_SDESC", "APLAN_PLAN_TYPE_LDESC", "APLAN_DECLARE_DT", "APLAN_CIP_CODE", "APLAN_HEGIS_CODE", "APLAN_SEQUENCE", "APLAN_REQ_TERM", "APLAN_REQ_TERM_SDESC", "APLAN_REQ_TERM_LDESC", "DW_STARTDATE", "DW_ENDDATE", "DW_ROWRANK", "DW_FIRSTROW", "DW_CURRENTROW") AS
  SELECT APROG_EMPLID,
       APROG_ACAD_CAREER,
       APROG_ACAD_CAREER_SDESC,
       APROG_ACAD_CAREER_LDESC,
       APROG_STDNT_CAR_NBR,
       APROG_EFFDT,
       APROG_EFFSEQ,
       APROG_INSTITUTION,
       APROG_INSTITUTION_SDESC,
       APROG_INSTITUTION_LDESC,
       APROG_ACAD_GROUP,
       APROG_ACAD_GROUP_SDESC,
       APROG_ACAD_GROUP_LDESC,
       APROG_ACAD_PROG,
       APROG_ACAD_PROG_SDESC,
       APROG_ACAD_PROG_LDESC,
       APROG_PROG_STATUS,
       APROG_PROG_STATUS_SDESC,
       APROG_PROG_STATUS_LDESC,
       APROG_PROG_ACTION,
       APROG_PROG_ACTION_SDESC,
       APROG_PROG_ACTION_LDESC,
       APROG_ACTION_DT,
       APROG_PROG_REASON,
       APROG_PROG_REASON_SDESC,
       APROG_PROG_REASON_LDESC,
       APROG_PROG_ADMIT_TERM,
       APROG_PROG_ADMIT_TERM_SDESC,
       APROG_PROG_ADMIT_TERM_LDESC,
       APROG_EXP_GRAD_TERM,
       APROG_EXP_GRAD_TERM_SDESC,
       APROG_EXP_GRAD_TERM_LDESC,
       APROG_REQ_TERM,
       APROG_REQ_TERM_SDESC,
       APROG_REQ_TERM_LDESC,
       APROG_CAMPUS,
       APROG_CAMPUS_SDESC,
       APROG_CAMPUS_LDESC,
       APROG_DEGR_CHECKOUT_STAT,
       APROG_DEGR_CHECKOUT_SDESC,
       APROG_DEGR_CHECKOUT_LDESC,
       APROG_ADM_APPL_NBR,
       APROG_APPL_PROG_NBR,
       APROG_CIP_CODE,
       APROG_HEGIS_CODE,
       APLAN_ACAD_PLAN,
       APLAN_ACAD_PLAN_SDESC,
       APLAN_ACAD_PLAN_LDESC,
       APLAN_ACAD_PLAN_TYPE,
       APLAN_PLAN_TYPE_SDESC,
       APLAN_PLAN_TYPE_LDESC,
       APLAN_DECLARE_DT,
       APLAN_CIP_CODE,
       APLAN_HEGIS_CODE,
       APLAN_SEQUENCE,
       APLAN_REQ_TERM,
       APLAN_REQ_TERM_SDESC,
       APLAN_REQ_TERM_LDESC,
       APROG_EFFDT AS DW_STARTDATE,
       DW_ENDDATE,
       DW_ROWRANK,
       DECODE(DW_ROWRANK,1,1,0) AS DW_FIRSTROW,
       NVL2(DW_ENDDATE,0,1) AS DW_CURRENTROW
       FROM (
       SELECT A.*,
       LEAD (
          APROG_EFFDT)
       OVER (
          PARTITION BY APROG_EMPLID, APROG_ACAD_CAREER, APROG_ACAD_PROG, APROG_PROG_ADMIT_TERM
          ORDER BY APROG_EFFDT)
          AS DW_ENDDATE,
       RANK () OVER (PARTITION BY APROG_EMPLID, APROG_ACAD_CAREER, APROG_ACAD_PROG, APROG_PROG_ADMIT_TERM ORDER BY APROG_EFFDT) AS DW_ROWRANK
  FROM SA.REC_ACAD_PROG_PLAN_S2 A);
--------------------------------------------------------
--  DDL for View TEST_SCORES_VW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "STUDENT_SUCCESS"."TEST_SCORES_VW" ("EMPLID", "TEST_ID", "MATH_TEST_SCORE", "VERBAL_TEST_SCORE", "TOTAL_TEST_SCORE") AS
  SELECT "EMPLID","TEST_ID","MATH_TEST_SCORE","VERBAL_TEST_SCORE","TOTAL_TEST_SCORE"
FROM
(select emplid, test_id, test_component, score from sa.cc_test_dtl a
WHERE test_dt =
  (SELECT MAX(test_dt)
  FROM sa.cc_test_dtl b
  WHERE a.emplid       = b.emplid
  AND a.test_id        = b.test_id
  AND a.test_component = b.test_component
  and test_id IN ('ACT','ELM','EPT','SAT')
  ))
  PIVOT
  (AVG(score) as test_score for test_component in ('MATH' as Math,'VERB' as Verbal,'TOTAL' as Total));